package gm22_9.segundaEntregaFIS;

import java.util.ArrayList;
import java.util.Hashtable;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : gm22_9_califyMe
//  @ File Name : CAsignatura.java
//  @ Date : 28/05/2020
//
//



/** Controlador de Asignaturas */
public class CAsignatura implements IAsignatura {

    private static CAsignatura instanciaUnica;
    private ArrayList<GUIAsignatura> guis;
    private VariablesGlobales var;
    private Hashtable<String, Asignatura> gestiona;

    
    /**
	 * Constructor privado de Singleton
	 */
	private CAsignatura() {
		guis = new ArrayList<>();
		var = VariablesGlobales.getInstance();
		gestiona = var.getAsignaturas();
	}
    
    //Getters & Setters



	public ArrayList<GUIAsignatura> getGuis() {
		return guis;
	}



	public void setGuis(ArrayList<GUIAsignatura> guis) {
		this.guis = guis;
	}



	public Hashtable<String, Asignatura> getGestiona() {
		return gestiona;
	}



	public void setGestiona(Hashtable<String, Asignatura> gestiona) {
		this.gestiona = gestiona;
	}

	//Metodos
    
	@Override
    public void agregarGUI(GUIAsignatura gui) {
    	guis.add(gui);
    }
    
    @Override
    public void removerGUI(GUIAsignatura gui) {
    	guis.remove(gui);
    }
	
	@Override
	public Asignatura getAsig(String nom) {
		Asignatura result = null;
		if (gestiona.containsKey(nom)) {
			result = gestiona.get(nom);
		}
		return result;
	}


	@Override
	public void matricularAlumno(String abrevAsignatura, Alumno al) {
		if (gestiona.containsKey(abrevAsignatura)) {
			gestiona.get(abrevAsignatura).matricularAlumno(al.getCorreo(), true);
			al.matricularEnAsig(abrevAsignatura);
		}
	}
	
	/**
	 * Devuelve la instancia unica del controlador
	 * @return instancia unica del controlador
	 */
	public static CAsignatura getInstanciaUnica() {
		if (instanciaUnica == null) {
			instanciaUnica = new CAsignatura();
		}
		return instanciaUnica;
	}

	@Override
	public void cargarVista(String abreviaturaAsig, IGestionProfesor sustitutoControladorUsuarios) {
		GUIAsignatura gui = new GUIAsignatura(instanciaUnica, sustitutoControladorUsuarios);
		this.agregarGUI(gui);
		gui.cargarVistaConDatos(getAsig(abreviaturaAsig));
	}
}
