package gm22_9.segundaEntregaFIS;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : gm22_9_califyMe
//  @ File Name : IAsigntura.java
//  @ Date : 28/05/2020
//
//

/**
 * Interfaz de la clase del controlador de Asignaturas
 *
 */
public interface IAsignatura {
	
	//No todos los metodos fueron implementados, solo aquellos que seran utiles para la implementacion de la segunda entrega
	
	/**
	 * Devuelve la asignatura buscada de existir
	 * @param nom Abreviacion de la asignatura
	 * @return la Asignatura buscada de existir
	 */
    public Asignatura getAsig(String nom);
    
    /**
     * Matricula al alumno en la asignatura
     * @param abrevAsignatura Abreviacion de la asignatura
     * @param al Alumno que sera matriculado
     */
    public void matricularAlumno(String abrevAsignatura, Alumno al);
    
    /**
     * Agrega la GUI a la lista del controlador para que este pueda monitorearla y notificarla de ser necesario.
     * No implementado del todo en esta version.
     * @param gui
     */
    public void agregarGUI(GUIAsignatura gui);
    
    /**
     * Remove la GUI a la lista del controlador para que este se olvide de monitorearla y notificarla.
     * No implementado del todo en esta version.
     * @param gui
     */
    public void removerGUI(GUIAsignatura gui);
    
    /**
     * Carga una vista de asignaturas
     * @param abreviaturaAsig
     * @param sustitutoControladorUsuarios permite recuperar informacion de los usuarios en esta version.
     */
    public void cargarVista(String abreviaturaAsig, IGestionProfesor sustitutoControladorUsuarios);
}
