package gm22_9.segundaEntregaFIS;

import java.sql.ResultSet;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : gm22_9_califyMe
//  @ File Name : IConectorBBDD.java
//  @ Date : 28/05/2020
//
//



/**
 * Interfaz del conector a la BBDD
 * @author luism
 *
 */
public interface IConectorBBDD {
    
    /**
     * Usar con sentencias SELECT, devuelve el resultado de la busqueda en forma de un ResultSet
     * @param sql Setencia a ejecutar
     * @return Resultado de la busqueda
     */
    public ResultSet ejecutarBusqueda(String sql);
    
    /**
     * Usar con sentencias que NO SEAN SELECT (INSERT, UPDATE y DELETE).
     * @param sql Sentencia a ejecutar
     */
    public void ejecutarOperacion(String sql);
}
