package gm22_9.segundaEntregaFIS;

import java.util.Hashtable;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : gm22_9_califyMe
//  @ File Name : IPersistenciaUsr.java
//  @ Date : 28/05/2020
//
//



/**
 * Interfaz de la clase que da persistencia a los usuarios
 *
 */
public interface IPersistenciaUsr {
    
	/**
	 * Crea a un nuevo usuario en la BBDD, distingue entre Profesores y Alumnos segun el correo.
	 * @param usr
	 */
    public void create(Usuario usr);
    
    /**
     * Recupera a un usuario de la BBDD buscando por su correo.
     * @param correo
     * @return devuelve null si no encuentra ninguno con ese correo.
     */
    public Usuario read(String correo);
    
    /**
     * Devuelve todas los usuarios de la BBDD
     * @return
     */
    public Hashtable<String, Usuario> readAll();
    
    /**
     * En esta version, solo actualiza la lista de asignaturas a las que esta matriculado un alumno
     * o a las que esta asociado un profesor.
     * @param oldId
     * @param newUsr
     */
    public void update(String oldId, Usuario newUsr);
    
    //Delete no sera implementado
    
    /**
     * Metodo que permite la inyeccion del modulo de conexion con la BBDD
     * @param conex
     */
    public void setConex(IConectorBBDD conex);
}
